export const DEFAULT_TAG='#20GQJGRJ0J';
export function normalizeTag(value){const tag='#'+String(value??'').trim().replace(/^#/,'').toUpperCase();if(!/^#[0289PYLQGRJCUV]{3,15}$/.test(tag))throw new Error('请输入正确的玩家标签，例如 #20GQJGRJ0J');return tag;}
export function cardBrief(c,idx){const icons={...(c.iconUrls||{})},evo=c.evolutionLevel!=null,champ=c.rarity==='champion',hero=!!icons.heroMedium&&!icons.evolutionMedium;let form='';if(idx==null){if(champ)form='hero';else if(evo)form=hero?'hero':'evo';}else if(idx===0&&evo)form='evo';else if(idx===1&&(champ||evo))form='hero';else if(idx===2){if(champ)form='hero';else if(evo)form=hero?'hero':'evo';}if(form==='evo'&&!icons.evolutionMedium&&c.name){const slug=c.name.toLowerCase().replace(/[.']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(slug)icons.evolutionMedium=`https://cdn.royaleapi.com/static/img/cards-150/${slug}-ev1.png`;}return {name:c.name??null,iconUrls:icons,elixir:c.elixirCost??null,rarity:c.rarity??null,evolutionLevel:c.evolutionLevel??null,form,isEvo:form==='evo',isHero:form==='hero'};}
export const towerBrief=c=>({name:c.name??null,iconUrls:c.iconUrls||{},level:c.level??null,maxLevel:c.maxLevel??null});
export const playerBrief=p=>({name:p.name||'',tag:p.tag||'',cards:(p.cards||[]).map(cardBrief),towers:(p.supportCards||[]).map(towerBrief)});
export function battleRow(b){const team=b.team?.[0]||{},opp=b.opponent?.[0]||{},tc=team.crowns||0,oc=opp.crowns||0;return {battleTime:b.battleTime||'',time:(b.battleTime||'').slice(0,15),mode:b.gameMode?.name||'',type:b.type||'',myCrowns:tc,oppCrowns:oc,result:tc>oc?'win':tc<oc?'loss':'draw',oppName:opp.name||'?',oppTag:opp.tag||'',myCards:(team.cards||[]).map(cardBrief),oppCards:(opp.cards||[]).map(cardBrief),myTowers:(team.supportCards||[]).map(towerBrief),oppTowers:(opp.supportCards||[]).map(towerBrief),myPlayers:(b.team||[]).map(playerBrief),oppPlayers:(b.opponent||[]).map(playerBrief)};}
const ranked=m=>[...m].sort((a,b)=>b[1]-a[1]);
export function summarize(battles){const modes=new Map(),cards=new Map();let wins=0,losses=0,draws=0;const rows=battles.map(b=>{const r=battleRow(b);if(r.result==='win')wins++;else if(r.result==='loss')losses++;else draws++;modes.set(r.mode,(modes.get(r.mode)||0)+1);for(const c of b.opponent?.[0]?.cards||[])cards.set(c.name,(cards.get(c.name)||0)+1);return r;});return {wins,losses,draws,winRate:wins+losses?Math.round(wins/(wins+losses)*1000)/10:0,modes:ranked(modes),topOpponentCards:ranked(cards).slice(0,15),battles:rows};}
export function recoverDeck(tag,battles,limit=20){const seen=new Map();for(const [idx,b] of battles.slice(0,limit).entries()){for(const p of b.team||[]){if(p.tag?.toUpperCase()!==tag||p.cards?.length!==8)continue;const sig=JSON.stringify(p.cards.map(c=>c.name));if(!p.cards.every(c=>c.name))continue;const row=seen.get(sig)||{count:0,idx,cards:p.cards,towers:p.supportCards||[]};row.count++;seen.set(sig,row);break;}}const best=[...seen.values()].sort((a,b)=>b.count-a.count||a.idx-b.idx)[0];return best?{cards:best.cards.map(cardBrief),towers:best.towers.map(towerBrief),sampleCount:best.count,sampleWindow:Math.min(limit,battles.length)}:null;}
